import { Routes } from '@angular/router';


export const routes: Routes = [
  { path: '', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent), pathMatch: 'full', title: 'PH Salary & Loan Calculators', data: { description: 'Free Philippines calculators for SSS, Pag-IBIG, PhilHealth, MPF contributions, salary net pay, tax, 13th month, and loan amortization.' } },
  { path: 'contributions', loadComponent: () => import('./features/contributions/contributions.component').then(m => m.ContributionsComponent), title: 'SSS, Pag-IBIG, PhilHealth, MPF', data: { description: 'Compute SSS, PhilHealth, Pag-IBIG, and MPF contributions with employee and employer shares.' } },
  { path: 'net-pay', loadComponent: () => import('./features/net-pay/net-pay.component').then(m => m.NetPayComponent), title: 'Salary Net Pay Calculators', data: { description: 'Estimate take-home pay with contributions, withholding tax, overtime, and optional holiday pays.' } },
  { path: '13th-month-pay', loadComponent: () => import('./features/thirteenth-month/thirteenth-month.component').then(m => m.ThirteenthMonthComponent), title: '13th Month Pay Calculator Philippines', data: { description: 'Compute your 13th-month pay with pro-rated calculator for resigned employees or new hires.' } },
  { path: 'mp2-calculator', loadComponent: () => import('./features/mp2/mp2.component').then(m => m.Mp2Component), title: 'Pag-IBIG MP2 Calculator', data: { description: 'Estimate your MP2 savings growth with annual payout or 5-year compounding options.' } },
  { path: 'amortization', loadComponent: () => import('./features/amortization/amortization.component').then(m => m.AmortizationComponent), title: 'Loan Amortization Calculators', data: { description: 'Calculate monthly payments and schedules for housing, car, and salary loans.' } },
  { path: 'sss-salary-loan', loadComponent: () => import('./features/sss-salary-loan/sss-salary-loan.component').then(m => m.SssSalaryLoanComponent), title: 'SSS Salary Loan Calculator', data: { description: 'Compute SSS salary loan net proceeds and monthly amortization.' } },
  { path: 'pagibig-housing-loan', loadComponent: () => import('./features/pagibig-housing-loan/pagibig-housing-loan.component').then(m => m.PagibigHousingLoanComponent), title: 'Pag-IBIG Housing Loan Calculator', data: { description: 'Estimate Pag-IBIG housing loan amortization based on 2026 rates.' } },
  { path: 'sss-maternity-benefit', loadComponent: () => import('./features/sss-maternity/sss-maternity.component').then(m => m.SssMaternityComponent), title: 'SSS Maternity Benefit Calculator', data: { description: 'Calculate your SSS maternity allowance and ADSC.' } },
  { path: 'tax-tables', loadComponent: () => import('./features/tax-tables/tax-tables.component').then(m => m.TaxTablesComponent), title: '2026 Tax Tables & SSS Contributions', data: { description: 'Official 2026 BIR Income Tax Tables and SSS Contribution Schedule with examples.' } },
  { path: 'about', loadComponent: () => import('./features/about/about.component').then(m => m.AboutComponent), title: 'About • PH Calculators', data: { description: 'About PH Calculators: mission, ownership, and transparency for AdSense compliance.' } },
  { path: 'contact', loadComponent: () => import('./features/contact/contact.component').then(m => m.ContactComponent), title: 'Contact • PH Calculators', data: { description: 'Contact PH Calculators for inquiries, feedback, or corrections.' } },
  { path: 'privacy-policy', loadComponent: () => import('./features/privacy-policy/privacy-policy.component').then(m => m.PrivacyPolicyComponent), title: 'Privacy Policy • PH Calculators', data: { description: 'Privacy Policy explaining how we handle data and cookies for PH Calculators.' } },
  { path: 'terms', loadComponent: () => import('./features/terms/terms.component').then(m => m.TermsComponent), title: 'Terms of Service • PH Calculators', data: { description: 'Terms and conditions for using PH Calculators.' } },
  { path: 'disclaimer', loadComponent: () => import('./features/disclaimer/disclaimer.component').then(m => m.DisclaimerComponent), title: 'Disclaimer • PH Calculators', data: { description: 'Financial disclaimer: informational purposes only, not financial or legal advice.' } },
  { path: 'articles', loadComponent: () => import('./features/articles/articles-list.component').then(m => m.ArticlesListComponent), title: 'Articles • PH Calculators', data: { description: 'Guides on SSS, Pag-IBIG, MPF, taxes, and loans in the Philippines.' } },
  { path: 'articles/sss-contribution-2026', loadComponent: () => import('./features/articles/sss-2026.component').then(m => m.Sss2026ArticleComponent), title: 'How to compute your SSS contribution in 2026', data: { description: 'Step-by-step guide to estimate SSS contributions in 2026 with examples.' } },
  { path: 'articles/pagibig-vs-mpf', loadComponent: () => import('./features/articles/pagibig-vs-mpf.component').then(m => m.PagibigVsMpfArticleComponent), title: 'Pag-IBIG vs MPF explained', data: { description: 'Understand differences between Pag-IBIG and SSS MPF, with pros/cons.' } },
  { path: 'articles/loan-amortization-ph', loadComponent: () => import('./features/articles/loan-amortization-ph.component').then(m => m.LoanAmortizationPhArticleComponent), title: 'How loan amortization works in the Philippines', data: { description: 'Guide to amortization basics, interest, principal, and sample schedules.' } },
  { path: '**', loadComponent: () => import('./features/not-found/not-found.component').then(m => m.NotFoundComponent), title: 'Page not found', data: { description: 'The page you’re looking for doesn’t exist.' } }
];
